//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogVarellaMotos.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BlogVarellaMotosEntities : DbContext
    {
        public BlogVarellaMotosEntities()
            : base("name=BlogManeEntities")
            //: base("name=BlogTestManeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BlogPost> BlogPost { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
    }
}
